NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "prompt"
  LORA_RANK: 4
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 10
  EPOCH_PERITER: 10
  WARMUP_EPOCH: 0
  TOTAL_EPOCH: 100
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "vit_fb_ppt_small_patch16_224"
  BATCH_SIZE: 32
SEED: None
